version: '3'

volumes: 
  home:

services:
  jupyter:
    build: .
    volumes:
      - home:/home/jovyan
      - $HOME/.ssh:/home/jovyan/.ssh
      - ..:/workspace:cached
    command: "start-notebook.sh \
        --ServerApp.root_dir=/workspace"
